name = "Darkhold Realms at War"
author = "The Komár Brothers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db061357fd1a63d6f4c470742a65275fa2d0fc0d3f2823b59e7f9704a5ff4a95"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
