name = "Darkhold Realms at War"
author = "The Komár Brothers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e359332bdd7b1019ce2ed91b8181b088dfa34011c1d164f4c2ef883659bacf7b"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
