name = "Darkhold"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dce742ed0c195e25ceffc49abcd2e2fb53c87289430085f4b687f071987fcdc"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
